name: yukimemo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.9.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  package_info_plus: ^1.4.0
  flutter_launcher_icons: ^0.9.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  uuid: ^3.0.6
  firebase_auth: ^3.3.11
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

aseets:
  - .env.development
  - .env.production

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"